server:
  port: 8080
spring:
  application:
    name: Web-Security-Hibernate

  datasource:
    url: jdbc:mysql://localhost:3306/Web-Security-DataBase
    username: root
    password: root


  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: update
